#!/usr/bin/env php
<?php

ini_set('display_errors', 'stderr');

require_once __DIR__ . '/../vendor/autoload.php';

use Spiral\Goridge\StreamRelay;
use Spiral\RoadRunner\PSR7Client;
use Spiral\RoadRunner\Worker;

use yii\Psr7\web\Application;

$relay = new StreamRelay(STDIN, STDOUT);
$psr7 = new PSR7Client(new Worker($relay));

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

$config = require_once __DIR__ . '/bootstrap.php';

while ($request = $psr7->acceptRequest()) {
    try {
        $application = (new Application($config, $request));
        $psr7->respond($application->handlePsr7Request());
        unset($application);
        gc_collect_cycles();
    } catch (\Throwable $e) {
        $psr7->getWorker()->error((string)$e);
    }
}